blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/toxicbishop/markdown-guide/discussions
    about: Ask questions or start a discussion about Markdown
